"""Build a figure catalogue for the STA258 ebook knowledge base.

Why this exists
---------------
Almost every figure in the book is *generated by R at build time*. The .Rmd source
contains ggplot code, not an image; the actual PNG only exists in the built site
under docs/Book_files/figure-html/. So a knowledge base built from .Rmd alone
contains no image URL anywhere, and the agent has nothing to show. Asked for a
picture it falls back to ASCII art.

This script reads the *built* HTML in docs/, pulls every <img> with its caption,
and writes knowledge/figures.md: a list of real, absolute image URLs on the
published GitHub Pages site. Upload that with the rest of the knowledge base and
the agent can embed figures with ordinary Markdown.

Run it after prepare_knowledge.py:

    python prepare_figures.py                      # downloads the book
    python prepare_figures.py --book-dir ../STA258_Book

Regenerate it whenever you rebuild the book: unlabelled R chunks produce names
like unnamed-chunk-12-1.png, and those numbers shift as chapters change.
"""

from __future__ import annotations

import argparse
import html as htmllib
import re
import urllib.parse
from pathlib import Path

from prepare_knowledge import download_repo

BOOK_BASE = "https://nishanmudalige.github.io/STA258_Book/"
DOCS_DIRNAME = "docs"

# docs/<page>.html -> the chapter label used in source_map.py
PAGE_TITLES = {
    "introduction.html": "Chapter 1: Introduction",
    "an-introduction-to-r.html": "Chapter 2: An Introduction to R",
    "descriptive-statistics.html": "Chapter 3: Descriptive Statistics",
    "foundations-of-inference.html": "Chapter 4: Foundations of Inference",
    "confidence-intervals.html": "Chapter 5: Confidence Intervals",
    "hypothesis-tests.html": "Chapter 6: Hypothesis Tests",
    "statistical-power.html": "Chapter 7: Statistical Power",
    "analysis-of-variance.html": "Chapter 8: Analysis of Variance",
    "simple-linear-regression.html": "Chapter 9: Simple Linear Regression",
    "analysis-of-categorical-data.html": "Chapter 10: Analysis of Categorical Data",
}

IMG_RE = re.compile(r"<img\b[^>]*>", re.I)
ATTR_RE = re.compile(r'(\w[\w-]*)\s*=\s*"([^"]*)"')
COMMENT_RE = re.compile(r"<!--.*?-->", re.S)


def attrs(tag: str) -> dict[str, str]:
    return {k.lower(): v for k, v in ATTR_RE.findall(tag)}


def absolutise(src: str) -> str:
    if src.startswith(("http://", "https://", "data:")):
        return src
    return BOOK_BASE + urllib.parse.quote(src.lstrip("./"), safe="/%")


def collect(docs: Path) -> dict[str, list[tuple[str, str]]]:
    """page title -> [(caption, absolute url)]"""
    out: dict[str, list[tuple[str, str]]] = {}

    for page, title in PAGE_TITLES.items():
        path = docs / page
        if not path.exists():
            print(f"  ! {page} not found in {docs} — skipping")
            continue

        raw = COMMENT_RE.sub("", path.read_text(encoding="utf-8", errors="replace"))
        rows: list[tuple[str, str]] = []
        seen: set[str] = set()

        for tag in IMG_RE.findall(raw):
            a = attrs(tag)
            src = a.get("src", "").strip()
            if not src or src.startswith("data:"):
                continue
            # Skip site furniture (logos, badges, buttons)
            if "/libs/" in src or "githubusercontent" in src or "shields.io" in src:
                continue

            url = absolutise(src)
            if url in seen:
                continue
            seen.add(url)

            caption = htmllib.unescape(a.get("alt") or "").strip()
            # Captions carry bookdown cross-references that mean nothing outside the book.
            caption = re.sub(r"(?:Figure|Table)\s+\\?@ref\((?:fig|tab):[^)]*\)",
                             "an earlier figure", caption)
            caption = re.sub(r"\\?@ref\((?:fig|tab):[^)]*\)", "an earlier figure", caption)
            caption = re.sub(r"\s{2,}", " ", caption).strip()
            if not caption:
                stem = Path(urllib.parse.unquote(src)).stem
                caption = re.sub(r"[-_]+", " ", stem).strip()
            rows.append((caption, url))

        if rows:
            out[title] = rows
    return out


def write_catalogue(catalogue: dict[str, list[tuple[str, str]]], out_path: Path) -> int:
    lines = [
        "<!-- ebook_agent retrieval copy; source: built ebook site (docs/) -->",
        "",
        "# Figure catalogue for the STA258 ebook",
        "",
        "Every figure published in the ebook, with its caption and its real image URL.",
        "",
        "**How to use this file.** When a figure would help the reader, embed it with a",
        "Markdown image whose URL is copied *exactly* from this catalogue, for example:",
        "",
        "    ![Boxplot of Additional Income Tax](" + BOOK_BASE + "Book_files/figure-html/unnamed-chunk-7-1.png)",
        "",
        "Do not invent image URLs, and do not modify the ones below.",
        "",
    ]

    total = 0
    for title, rows in catalogue.items():
        lines.append(f"## {title}")
        lines.append("")
        for caption, url in rows:
            lines.append(f"- **{caption}** — `{url}`")
            total += 1
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--book-dir", type=Path, help="Path to a local STA258_Book clone")
    ap.add_argument("--output-dir", type=Path, default=Path("knowledge"))
    args = ap.parse_args()

    if args.book_dir:
        book_dir = args.book_dir.expanduser().resolve()
    else:
        print("Downloading current ebook source from GitHub …")
        book_dir = download_repo()

    docs = book_dir / DOCS_DIRNAME
    if not docs.exists():
        raise SystemExit(
            f"No built site at {docs}.\n"
            "Figures only exist once the book has been rendered, so build the book "
            "(bookdown::render_book()) and make sure docs/ is committed."
        )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    catalogue = collect(docs)
    out_path = args.output_dir.resolve() / "figures.md"
    total = write_catalogue(catalogue, out_path)

    print(f"\nWrote {out_path}")
    print(f"{total} figures across {len(catalogue)} chapters:")
    for title, rows in catalogue.items():
        print(f"  {len(rows):>3}  {title}")


if __name__ == "__main__":
    main()
